//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class student_performanceEntities : DbContext
    {
        public student_performanceEntities()
            : base("name=student_performanceEntities")
        {
        }
        private static student_performanceEntities _context;

        public static student_performanceEntities GetContext()
        {
            if (_context == null)
            {
                _context = new student_performanceEntities();
            }

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ведомости_успеваемости> Ведомости_успеваемости { get; set; }
        public virtual DbSet<Дисциплины> Дисциплины { get; set; }
        public virtual DbSet<Кафедры> Кафедры { get; set; }
        public virtual DbSet<Преподаватели> Преподаватели { get; set; }
        public virtual DbSet<Студенты> Студенты { get; set; }
        public virtual DbSet<teachersmoll> teachersmoll { get; set; }
    }
}
