//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ведомости_успеваемости
    {
        public int Код_успеваемости { get; set; }
        public int Код_студента { get; set; }
        public int Код_дисциплины { get; set; }
        public Nullable<int> Код_преподавателя { get; set; }
        public int Оценка { get; set; }
        public System.DateTime Дата { get; set; }
    
        public virtual Дисциплины Дисциплины { get; set; }
        public virtual Преподаватели Преподаватели { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}
