//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Дисциплины
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Дисциплины()
        {
            this.Ведомости_успеваемости = new HashSet<Ведомости_успеваемости>();
        }
    
        public int Код_дисциплины { get; set; }
        public string Название_дисциплины { get; set; }
        public int Номер_кафедры { get; set; }
        public int Код_преподавателя { get; set; }
        public int Количество_часов { get; set; }
        public string Вид_итогового_контроля { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ведомости_успеваемости> Ведомости_успеваемости { get; set; }
        public virtual Кафедры Кафедры { get; set; }
        public virtual Кафедры Кафедры1 { get; set; }
        public virtual Преподаватели Преподаватели { get; set; }
    }
}
