//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Кафедры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Кафедры()
        {
            this.Дисциплины = new HashSet<Дисциплины>();
            this.Дисциплины1 = new HashSet<Дисциплины>();
            this.Преподаватели = new HashSet<Преподаватели>();
            this.Студенты = new HashSet<Студенты>();
        }
    
        public int Код_Кафедры { get; set; }
        public string Название_кафедры { get; set; }
        public string Факультет { get; set; }
        public string ФИО_заведующего { get; set; }
        public int Код_комнаты { get; set; }
        public int Код_корпуса { get; set; }
        public string Телефон { get; set; }
        public Nullable<int> Количество_преподавателей { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Дисциплины> Дисциплины { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Дисциплины> Дисциплины1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Преподаватели> Преподаватели { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студенты> Студенты { get; set; }
    }
}
