//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Преподаватели
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Преподаватели()
        {
            this.Ведомости_успеваемости = new HashSet<Ведомости_успеваемости>();
            this.Дисциплины = new HashSet<Дисциплины>();
        }
    
        public int Код_преподавателя { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int Код__кафедры { get; set; }
        public System.DateTime Год_рождения { get; set; }
        public System.DateTime Год_поступления_на_работу { get; set; }
        public Nullable<int> Стаж { get; set; }
        public string Должность { get; set; }
        public string Пол { get; set; }
        public string Адрес { get; set; }
        public string Город { get; set; }
        public string Телефон { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ведомости_успеваемости> Ведомости_успеваемости { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Дисциплины> Дисциплины { get; set; }
        public virtual Кафедры Кафедры { get; set; }
    }
}
